import React from "react";
import img1 from "../../assets/img/img2.jpg";
import img4 from "../../assets/img/img4.jpg";
import img5 from "../../assets/img/img5.jpg";

const SampleBooks = () => {
  return (
    <section className=" py-16">
      <div className="container mx-auto text-center text-white">
        <h1 className="text-3xl font-semibold mb-4 text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-blue-600">
          Sample Books Generated by BookAI
        </h1>
        <p className="text-lg mb-8">
          Explore some of the captivating books created using our AI technology.
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 space-x-2">
          {/* Card 1 */}
          <div className=" backdrop-blur-sm p-6 bg-white/10 rounded-lg shadow-lg transition-all duration-300 hover:scale-110">
            <img
                src={img1}
              alt="The Quantum Paradox"
              className="w-full h-[700px] object-cover rounded-lg mb-4"
            />

            <h3 className="text-xl font-semibold mb-2">Science Fiction</h3>
            <p className="text-gray-300 mb-4">
              "As Dr. Elara stepped through the shimmering portal, she knew
              there was no turning back. The fate of two universes now rested in
              her hands..."
            </p>
            <a
              href="#!"
              className="text-purple-400 font-semibold hover:underline"
            >
              Read More
            </a>
          </div>

          {/* Card 2 */}
          <div className="backdrop-blur-sm  bg-white/10  p-6 rounded-lg shadow-lg transition-all duration-300 hover:scale-110">
            <img
             src={img5}
              alt="Whispers in the Mist"
              className="w-full h-[700px] object-cover rounded-lg mb-4"
            />
            <h3 className="text-xl font-semibold mb-2">Mystery</h3>
            <p className="text-gray-300 mb-4">
              "The old lighthouse stood silent, its beacon long extinguished.
              But on foggy nights, some swore they could still see its ghostly
              light..."
            </p>
            <a
              href="#!"
              className="text-purple-400 font-semibold hover:underline"
            >
              Read More
            </a>
          </div>

          {/* Card 3 */}
          <div className="backdrop-blur-sm  bg-white/10  p-6 rounded-lg shadow-lg transition-all duration-300 hover:scale-110">
            <img
          src={img4}
              alt="Echoes of Eternity"
              className="w-full h-[700px] object-cover rounded-lg mb-4"
            />
            <h3 className="text-xl font-semibold mb-2">Fantasy</h3>
            <p className="text-gray-300 mb-4">
              "The ancient prophecy spoke of a child born with starlight in
              their eyes. As the comet blazed overhead, the kingdom held its
              breath..."
            </p>
            <a
              href="#!"
              className="text-purple-400 font-semibold hover:underline"
            >
              Read More
            </a>
          </div>
        </div>
      </div>
    </section>
  );
};

export default SampleBooks;
